name: build actions
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-16.04
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm i -g @zeit/ncc
      - name: Debug workspace
        run: env
      - name: Install commit
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-git/commit
      - name: Install tag
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-git/tag
      - uses: navikt/bidrag-git/commit@v3.0.3
        with:
          commit_message: "${{ steps.now.outputs.timestamp }}: Build of actions with npm and ncc"
          pattern: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
