name: build actions
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '13.x'
      - run: npm i -g @zeit/ncc
      - name: Debug workspace
        run: env
      - name: Install git-commit
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/git-commit
      - name: Install git-commit-n-tag
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/git-commit-n-tag
      - name: Install git-tag
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/git-tag
      - name: Install git-tag-snapshot
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/git-tag-snapshot
      - name: Install maven-deploy
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/maven-deploy
      - name: Install maven-prepare-deploy
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/maven-prepare-deploy
      - name: Install maven-setup
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/maven-setup
      - name: Install maven-verify-dependencies
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/maven-verify-dependencies
      - name: Install maven-verify-deploy
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/maven-verify-deploy
      - name: Install node-build-action
        uses: jactor-rises/actions/node-build-action@v2.0.0-node-build-action
        with:
          artifact_folder: actions/node-build-action
      - name: Generate timestamp
        id: now
        run: echo ::set-output name=timestamp::$(date +"%Y-%m-%d:%T")
      - uses: jactor-rises/actions/git-commit@v2.0.0-node-build-action
        with:
          commit_message: "node-build-action@${{ steps.now.outputs.timestamp }}"
          pattern: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
